type Project @table {
  name: String!
  projectId: UUID!
  createdAt: Timestamp!
  description: String
  owner: User
}

type Deployment @table {
  deploymentId: UUID!
  project: Project!
  user: User!
  status: String!
  startTime: Timestamp!
  endTime: Timestamp
  logUrl: String
  versionTag: String
}

type DeploymentService @table {
  serviceName: String!
  status: String!
  deployment: Deployment!
  details: String
}

type User @table {
  email: String!
  displayName: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Permission @table(key: ["user", "project"]) {
  user: User!
  project: Project!
  role: String!
}